### ISSUE TITLE
Provide PHP 8 dlls for Windows? (none available on https://pecl.php.net/package/runkit7/3.1.0a1/windows)

### ISSUE THREAD

**Issue by batata004** [runkit7/runkit7#250]
Hi my friend @TysonAndre ! How are you doing? Hope you are fine 

I am opening this support issue in order to request, if possible, the PHP 8 version of this nice extension! On the link https://pecl.php.net/package/runkit7/3.1.0a1/windows there is only the PHP 7.x versions. Would it be possible for you to provide the `php_runkit7.dll` file so I can use with PHP 8?

Thank you so much!

**Comment by TysonAndre** [comment]
That's an issue with the Windows build infrastructure - None of the extensions on pecl.php.net have any builds for php 8.0 yet. I think the windows.php.net team is already working on it but don't know when it would be finished - e.g. https://pecl.php.net/package/xdebug/3.0.0/windows supports php 8.0
- You may want to wait until they fix it to start using php 8 on windows - otherwise, see https://github.com/runkit7/runkit7#building-and-installing-runkit7-in-windows

The php project used to have hosting and assistance with fixing builds for all of the pecl extensions

https://www.techrepublic.com/article/microsoft-to-discontinue-windows-builds-of-php-programming-language/

**Comment by TysonAndre** [comment]
Oh, there's a new version - https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2#building_pecl_extensions

**Comment by batata004** [comment]
Thank you a lot, you are always helpful my friend and always provide lots of good information. After reading everything you gave me, I think I will just have to wait pecl to compile the PHP 8 version, despite I am in a hurry. So I will downgrade back to PHP 7.4 in order to keep using this awesome extension! I cant live without it.

**Comment by TysonAndre** [comment]
> I think the windows.php.net team is already working on it but don't know when it would be finished

Supposedly going to take a few more weeks for them to set things up and trigger builds for php 8 according to posts on the mailing list, but it's still planned by that team

**Comment by batata004** [comment]
Thank you so much, so I will be waiting! Have a nice sunday :)

**Comment by TysonAndre** [comment]
I checked again today, https://pecl.php.net/package/runkit7/4.0.0a2/windows now has builds for PHP 8.0 on Windows.

If you see any issues specific to PHP 8.0 that didn't happen in 7.4 and aren't found in the README, please file a new issue

**Comment by batata004** [comment]
THANK YOU SO MUCH MY FRIEND!!!!!!!!!
